// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI;

namespace WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211218120023_Insert_seed")]
    partial class Insert_seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.CChiTietSanPham", b =>
                {
                    b.Property<string>("MaCTSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("GioTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SL")
                        .HasColumnType("int");

                    b.Property<string>("SanPhamMaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCTSP");

                    b.HasIndex("SanPhamMaSP");

                    b.ToTable("ChiTietSanPhams");

                    b.HasData(
                        new
                        {
                            MaCTSP = "CTSP_01",
                            Anh = "",
                            Color = "Trắng, Xanh, Vàng",
                            DonGia = 30.0,
                            GioTinh = "Nam",
                            MoTaSP = "",
                            SL = 10,
                            SanPhamMaSP = "SP_1",
                            Size = "M,X,XL"
                        },
                        new
                        {
                            MaCTSP = "CTSP_02",
                            Anh = "",
                            Color = "Đen, Xanh",
                            DonGia = 30.0,
                            GioTinh = "Nam",
                            MoTaSP = "",
                            SL = 10,
                            SanPhamMaSP = "SP_2",
                            Size = "M,X"
                        },
                        new
                        {
                            MaCTSP = "CTSP_03",
                            Anh = "",
                            Color = "Xám, Đen, Vàng, Lục",
                            DonGia = 30.0,
                            GioTinh = "Nữ",
                            MoTaSP = "",
                            SL = 10,
                            SanPhamMaSP = "SP_3",
                            Size = "S,M"
                        },
                        new
                        {
                            MaCTSP = "CTSP_04",
                            Anh = "",
                            Color = "Trắng, Đen, Đỏ, Xanh",
                            DonGia = 30.0,
                            GioTinh = "UniSex",
                            MoTaSP = "",
                            SL = 10,
                            SanPhamMaSP = "SP_4",
                            Size = "S,M,X"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.CSanPham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Delete_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSp");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            MaSp = "SP_1",
                            Delete_Date = new DateTime(2021, 12, 18, 19, 0, 22, 810, DateTimeKind.Local).AddTicks(1169),
                            LoaiSanPham = "Áo",
                            Status = true,
                            TenSP = "Áo thun đi biển",
                            Update_Date = new DateTime(2021, 12, 18, 19, 0, 22, 808, DateTimeKind.Local).AddTicks(9044)
                        },
                        new
                        {
                            MaSp = "SP_2",
                            Delete_Date = new DateTime(2021, 12, 18, 19, 0, 22, 811, DateTimeKind.Local).AddTicks(9651),
                            LoaiSanPham = "quần",
                            Status = true,
                            TenSP = "quần bơi",
                            Update_Date = new DateTime(2021, 12, 18, 19, 0, 22, 811, DateTimeKind.Local).AddTicks(9630)
                        },
                        new
                        {
                            MaSp = "SP_3",
                            Delete_Date = new DateTime(2021, 12, 18, 19, 0, 22, 811, DateTimeKind.Local).AddTicks(9834),
                            LoaiSanPham = "Áo",
                            Status = true,
                            TenSP = "Áo thun tay dài",
                            Update_Date = new DateTime(2021, 12, 18, 19, 0, 22, 811, DateTimeKind.Local).AddTicks(9830)
                        },
                        new
                        {
                            MaSp = "SP_4",
                            Delete_Date = new DateTime(2021, 12, 18, 19, 0, 22, 811, DateTimeKind.Local).AddTicks(9874),
                            LoaiSanPham = "Áo",
                            Status = true,
                            TenSP = "Áo thun tay ngắn",
                            Update_Date = new DateTime(2021, 12, 18, 19, 0, 22, 811, DateTimeKind.Local).AddTicks(9871)
                        });
                });

            modelBuilder.Entity("WebAPI.Models.CChiTietSanPham", b =>
                {
                    b.HasOne("WebAPI.Models.CSanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamMaSP");

                    b.Navigation("SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
